version: '3.8'

services:
  flashover:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashover
    ports:
      - "8080:8080"
    volumes:
      # Persist SQLite database
      - ./db:/app/db
      # Mount .env file for configuration
      - ./backend/.env:/app/.env
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped

# For development with hot reload (optional, run separately)
  flashover-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashover-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./db:/app/db
      - ./backend/.env:/app/.env
    environment:
      - ENVIRONMENT=development
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    profiles:
      - dev
